name: SkillGrinds
version: '${project.version}'
main: dev.ng5m.skillgrinds.SkillGrinds
api-version: '1.20'
commands:
  skillgrindsmanager:
    aliases:
      - sgm

    permission: ng5m.skillgrinds.sgm
    usage: /<command> [option] [action] [value]
  customvillager:
    permission: ng5m.skillgrinds.cv
    usage: /<command> [name]
